


USE MASTER;  
GO  


CREATE DATABASE SELLSYSTEM;
GO
USE SELLSYSTEM
GO
CREATE TABLE EMPLOYEE (
员工编号 INT PRIMARY KEY IDENTITY(1,1),
员工姓名 NVARCHAR(10),
员工电话 NVARCHAR(20),
员工地址 NVARCHAR(100)
)

CREATE TABLE MANUFACTURER(
厂商编号 INT PRIMARY KEY IDENTITY(0,1),
厂商名称 NVARCHAR(20) UNIQUE  NOT NULL,
法人代表 NVARCHAR(10),
电话 NVARCHAR(20),
厂商地址 NVARCHAR(100)
)
CREATE TABLE GOODS(
商品编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
总金额 MONEY DEFAULT 0,
进货年 SMALLINT DEFAULT DATEPART(YYYY,GETDATE()),
进货月 SMALLINT DEFAULT DATEPART(MM,GETDATE()),
进货日 SMALLINT DEFAULT DATEPART(DD,GETDATE()),
业务员编号 INT,
CONSTRAINT FK_GOODS_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_GOODS_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称)
)




CREATE TABLE RETREAT(
退货编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
总金额 MONEY DEFAULT 0,
退货年 SMALLINT DEFAULT DATEPART(YYYY,GETDATE()),
退货月 SMALLINT DEFAULT DATEPART(MM,GETDATE()),
退货日 SMALLINT DEFAULT DATEPART(DD,GETDATE()),
业务员编号 INT,
CONSTRAINT FK_RETREAT_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_RETREAT_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称)
)

CREATE TABLE SELL(
商品编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
总金额 MONEY DEFAULT 0,
销售年 SMALLINT DEFAULT DATEPART(YYYY,GETDATE()),
销售月 SMALLINT DEFAULT DATEPART(MM,GETDATE()),
销售日 SMALLINT DEFAULT DATEPART(DD,GETDATE()),
业务员编号 INT,
CONSTRAINT FK_SELL_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_SELL_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称)
)

CREATE TABLE USERDB(
用户编号 INT PRIMARY KEY IDENTITY(1,1),
用户名 NVARCHAR(10) NOT NULL UNIQUE,
密码 NVARCHAR(10) NOT NULL
)



--VIEW
USE SELLSYSTEM
GO

CREATE VIEW ADD_THISDAY
AS(
SELECT *
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  进货日 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
)

GO

CREATE VIEW ADD_THISMONTH AS(
SELECT *
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
)

GO

CREATE VIEW ADD_THISSEASON AS(
SELECT *
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号),'-',(SELECT 进货月 FROM GOODS WHERE 商品编号=A.商品编号),'-',(SELECT  进货日 FROM GOODS WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
)

GO
CREATE VIEW ADD_THISYEAR AS(
SELECT *
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
)
GO


CREATE VIEW ADD_THISSEASON_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号),'-',(SELECT  进货月 FROM GOODS WHERE 商品编号=A.商品编号),'-',(SELECT  进货日 FROM GOODS WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
GROUP BY 生产厂商
)


GO


CREATE VIEW ADD_THISMONTH_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
GROUP BY 生产厂商
)
GO

CREATE VIEW ADD_THISYEAR_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
GROUP BY 生产厂商
)
GO

CREATE VIEW ADD_THISDAY_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM GOODS  AS A
WHERE (SELECT 进货年 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  进货日 FROM GOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
GROUP BY 生产厂商
)
GO







CREATE VIEW SELL_THISDAY
AS(
SELECT *
FROM SELL  AS A 
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
)

GO

CREATE VIEW SELL_THISMONTH AS(
SELECT *
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
)
GO

CREATE VIEW SELL_THISSEASON AS(
SELECT *
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
)
GO


CREATE VIEW SELL_THISYEAR AS(
SELECT *
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
)

GO

CREATE VIEW SELL_THISSEASON_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT  销售月 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
GROUP BY 生产厂商
)
GO


CREATE VIEW SELL_THISMONTH_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
GROUP BY 生产厂商
)
GO


CREATE VIEW SELL_THISYEAR_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
GROUP BY 生产厂商
)

GO

CREATE VIEW SELL_THISDAY_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
GROUP BY 生产厂商
)
GO



CREATE VIEW QUERY_EMPLOYEESELL AS(
SELECT E.员工编号 AS 业务员编号, E.员工姓名 AS 员工姓名,  ISNULL(总金额,0) AS 销售总金额  
FROM(
	SELECT S.业务员编号 AS 业务员编号 ,SUM(S.总金额) AS 总金额
	FROM SELL AS S
	GROUP BY 业务员编号
	) AS X  RIGHT JOIN EMPLOYEE  AS E ON X.业务员编号=E.员工编号
	)
GO

CREATE VIEW GOODSQREMAIN AS(
SELECT  G.商品名 AS 商品名,G.型号 AS 型号,G.生产厂商 AS 生产厂商,G.数量-S.数量 AS 数量
FROM  
(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM GOODS GROUP BY 商品名,型号,生产厂商 ) AS G ,(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM SELL GROUP BY 商品名,型号,生产厂商 ) AS S
WHERE G.商品名=S.商品名 AND G.型号=S.型号 AND G.生产厂商=S.生产厂商

UNION

SELECT  商品名, 型号, 生产厂商,数量
FROM  (SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM GOODS GROUP BY 商品名,型号,生产厂商 )AS GOODS
WHERE  商品名 NOT IN   (SELECT G.商品名 AS 商品名 FROM		(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM GOODS GROUP BY 商品名,型号,生产厂商 ) AS G ,(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM SELL GROUP BY 商品名,型号,生产厂商 ) AS S WHERE G.商品名=S.商品名 AND G.型号=S.型号 AND G.生产厂商=S.生产厂商) 
	OR 型号  NOT IN    (SELECT G.型号 FROM					(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM GOODS GROUP BY 商品名,型号,生产厂商 ) AS G ,(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM SELL GROUP BY 商品名,型号,生产厂商 ) AS S WHERE G.商品名=S.商品名 AND G.型号=S.型号 AND G.生产厂商=S.生产厂商)  
    OR 生产厂商 NOT IN (SELECT G.生产厂商 AS 生产厂商 FROM  (SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM GOODS GROUP BY 商品名,型号,生产厂商 ) AS G ,(SELECT 商品名,型号,生产厂商,SUM(数量) AS 数量 FROM SELL GROUP BY 商品名,型号,生产厂商 ) AS S WHERE G.商品名=S.商品名 AND G.型号=S.型号 AND G.生产厂商=S.生产厂商)

	)
	
	GO
	
--插入数值
USE SELLSYSTEM
GO
INSERT INTO  USERDB (用户名,密码)VALUES('YY','YY')
INSERT INTO  MANUFACTURER VALUES('李明','MFC','110','河南省南阳市')

GO
