
USE MASTER;  
GO 

CREATE DATABASE SELLSYSTEM;
GO
USE SELLSYSTEM
GO
CREATE TABLE EMPLOYEE (
员工编号 INT PRIMARY KEY IDENTITY(1,1),
员工姓名 NVARCHAR(10),
员工电话 NVARCHAR(20),
员工地址 NVARCHAR(100)
)
GO

CREATE TABLE MANUFACTURER(
厂商编号 INT PRIMARY KEY IDENTITY(1,1),
厂商名称 NVARCHAR(20) UNIQUE  NOT NULL,
法人代表 NVARCHAR(10),
电话 NVARCHAR(20),
厂商地址 NVARCHAR(100)
)

GO
CREATE TABLE GOODSREMAIN (
商品编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
业务员编号 INT,
CONSTRAINT FK_GOODSREMAIN_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_GOODSREMAIN_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称),
UNIQUE(生产厂商,商品名,型号)
)
GO

CREATE TABLE ADDGOODS(
商品编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
总金额 MONEY DEFAULT 0,
进货年 SMALLINT DEFAULT DATEPART(YYYY,GETDATE()),
进货月 SMALLINT DEFAULT DATEPART(MM,GETDATE()),
进货日 SMALLINT DEFAULT DATEPART(DD,GETDATE()),
业务员编号 INT,
CONSTRAINT FK_GOODS_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_GOODS_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称)
)
GO

CREATE TABLE RETREAT(
退货编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
总金额 MONEY DEFAULT 0,
退货年 SMALLINT DEFAULT DATEPART(YYYY,GETDATE()),
退货月 SMALLINT DEFAULT DATEPART(MM,GETDATE()),
退货日 SMALLINT DEFAULT DATEPART(DD,GETDATE()),
业务员编号 INT,
CONSTRAINT FK_RETREAT_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_RETREAT_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称)
)

GO

CREATE TABLE SELL(
商品编号 INT PRIMARY KEY IDENTITY(1,1),
生产厂商 NVARCHAR(20),
商品名 NVARCHAR(20),
型号 NVARCHAR(20),
单价 MONEY  DEFAULT 0,
数量 INT DEFAULT 0,
总金额 MONEY DEFAULT 0,
销售年 SMALLINT DEFAULT DATEPART(YYYY,GETDATE()),
销售月 SMALLINT DEFAULT DATEPART(MM,GETDATE()),
销售日 SMALLINT DEFAULT DATEPART(DD,GETDATE()),
业务员编号 INT,
CONSTRAINT FK_SELL_EMPLOYEE FOREIGN KEY (业务员编号) REFERENCES EMPLOYEE(员工编号),
CONSTRAINT FK_SELL_MANUFACTURER FOREIGN KEY (生产厂商) REFERENCES MANUFACTURER(厂商名称)
)

CREATE TABLE USERDB(
用户编号 INT PRIMARY KEY IDENTITY(1,1),
用户名 NVARCHAR(10) NOT NULL UNIQUE,
密码 NVARCHAR(10) NOT NULL
)

GO


CREATE VIEW ADD_THISDAY
AS(
SELECT *
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  进货日 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
)

GO

CREATE VIEW ADD_THISMONTH AS(
SELECT *
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
)

GO

CREATE VIEW ADD_THISSEASON AS(
SELECT *
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号),'-',(SELECT 进货月 FROM ADDGOODS WHERE 商品编号=A.商品编号),'-',(SELECT  进货日 FROM ADDGOODS WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
)

GO
CREATE VIEW ADD_THISYEAR AS(
SELECT *
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
)
GO


CREATE VIEW ADD_THISSEASON_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号),'-',(SELECT  进货月 FROM ADDGOODS WHERE 商品编号=A.商品编号),'-',(SELECT  进货日 FROM ADDGOODS WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
GROUP BY 生产厂商
)


GO


CREATE VIEW ADD_THISMONTH_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
GROUP BY 生产厂商
)
GO

CREATE VIEW ADD_THISYEAR_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
GROUP BY 生产厂商
)
GO

CREATE VIEW ADD_THISDAY_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM ADDGOODS  AS A
WHERE (SELECT 进货年 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 进货月 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  进货日 FROM ADDGOODS WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
GROUP BY 生产厂商
)
GO




CREATE VIEW SELL_THISDAY
AS(
SELECT *
FROM SELL  AS A 
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
)

GO

CREATE VIEW SELL_THISMONTH AS(
SELECT *
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
)
GO

CREATE VIEW SELL_THISSEASON AS(
SELECT *
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
)
GO


CREATE VIEW SELL_THISYEAR AS(
SELECT *
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
)

GO

CREATE VIEW SELL_THISSEASON_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE())) 
   AND		(SELECT DATEPART(QQ,CONCAT((SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT  销售月 FROM SELL WHERE 商品编号=A.商品编号),'-',(SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号))))
		  = (SELECT DATEPART(QQ,GETDATE()))
GROUP BY 生产厂商
)
GO


CREATE VIEW SELL_THISMONTH_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
GROUP BY 生产厂商
)
GO


CREATE VIEW SELL_THISYEAR_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
GROUP BY 生产厂商
)

GO

CREATE VIEW SELL_THISDAY_GROUP AS(
SELECT A.生产厂商,SUM(A.总金额) AS 总金额
FROM SELL  AS A
WHERE (SELECT 销售年 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(YY,GETDATE()))
AND (SELECT 销售月 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(MM,GETDATE()) )
AND (SELECT  销售日 FROM SELL WHERE 商品编号=A.商品编号)=(SELECT DATEPART(DD,GETDATE()))
GROUP BY 生产厂商
)
GO



CREATE VIEW QUERY_EMPLOYEESELL AS(
SELECT E.员工编号 AS 业务员编号, E.员工姓名 AS 员工姓名,  ISNULL(总金额,0) AS 销售总金额  
FROM(
	SELECT S.业务员编号 AS 业务员编号 ,SUM(S.总金额) AS 总金额
	FROM SELL AS S
	GROUP BY 业务员编号
	) AS X  RIGHT JOIN EMPLOYEE  AS E ON X.业务员编号=E.员工编号
	)
GO





USE SELLSYSTEM
GO
INSERT INTO  USERDB (用户名,密码)VALUES('YY','YY')
INSERT INTO  USERDB (用户名,密码)VALUES('0','0')
INSERT INTO  USERDB (用户名,密码)VALUES('admin','123')

INSERT INTO MANUFACTURER VALUES('nokia','sss','18262666110','河南省南阳市')
INSERT INTO MANUFACTURER VALUES('DS','LIMING','1512222','重庆市');
INSERT INTO MANUFACTURER VALUES('xm','l','48812922','北京市');
INSERT INTO MANUFACTURER VALUES('hw','r','151592','广州市');

INSERT INTO EMPLOYEE VALUES('ZZ','110191999','云南省');
INSERT INTO EMPLOYEE VALUES('SDG','119110','四川省');
INSERT INTO EMPLOYEE VALUES('ASFG','11521990','北京市');
INSERT INTO EMPLOYEE VALUES('ARG','9292110','黑龙江省');

INSERT INTO GOODSREMAIN VALUES('DS','手机','8250',5888,20,1);
INSERT INTO GOODSREMAIN VALUES('nokia','手机','8250',998,20,2);
INSERT INTO GOODSREMAIN VALUES('hw','手机','v20',4888,30,3);
INSERT INTO GOODSREMAIN VALUES('xm','手机','m10',5999,50,2);

INSERT INTO ADDGOODS VALUES('xm','手机','m10',5999,10,59990,(SELECT (DATEPART(YYYY,GETDATE()))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('xm','手机','m10',5999,1,5999,(SELECT (DATEPART(YYYY,GETDATE()-1))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('xm','手机','m10',5999,9,53991,(SELECT (DATEPART(YYYY,GETDATE()-2))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('xm','手机','m10',5999,10,59999,(SELECT (DATEPART(YYYY,GETDATE()))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('xm','手机','m10',5999,10,59999,(SELECT (DATEPART(YYYY,GETDATE()-6))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('hw','手机','m10',5999,10,59999,(SELECT (DATEPART(YYYY,GETDATE()))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('xm','手机','v20',4888,10,48880,(SELECT (DATEPART(YYYY,GETDATE()))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('hw','手机','v20',4888,20,97760,(SELECT (DATEPART(YYYY,GETDATE()-2))),(SELECT (DATEPART(MM,GETDATE())-1)),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('nokia','手机','8250',998,20,19960,(SELECT (DATEPART(YYYY,GETDATE()))),(SELECT (DATEPART(MM,GETDATE()))),(SELECT (DATEPART(DD,GETDATE())-1)),1);
INSERT INTO ADDGOODS VALUES('DS','手机','8250',5888,20,117730,(SELECT (DATEPART(YYYY,GETDATE()))),(SELECT (DATEPART(MM,GETDATE())-1)),(SELECT (DATEPART(DD,GETDATE())-1)),1);


INSERT INTO SELL VALUES('DS','手机','8250',5888,20,117730,2021,12,18,2);
INSERT INTO SELL VALUES('hw','手机','v20',5888,20,117730,2021,12,15,2);
INSERT INTO SELL VALUES('nokia','手机','8250',5888,20,117730,2021,11,15,2);
INSERT INTO SELL VALUES('nokia','手机','8250',5888,20,117730,2021,12,15,2);
INSERT INTO SELL VALUES('nokia','手机','8250',5888,20,117730,2021,12,15,2);
INSERT INTO SELL VALUES('nokia','手机','8250',5888,20,117730,2021,12,15,2);



